# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set working directory inside the container
WORKDIR /app

# Copy requirements first for caching dependencies
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your app code
COPY . .

# Expose the port
EXPOSE 8000

# Run the app with Uvicorn
CMD ["sh", "-c", "uvicorn main:app --host=0.0.0.0 --port ${PORT:-8000}"]
