# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set working directory inside the container
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 80

# Run the app with Uvicorn
CMD ["sh", "-c", "uvicorn main:app --host=0.0.0.0 --port ${PORT:-80}"]
